<?php
			$optionsArray = array( 'totals' => array( 'Id' => array( 'totalsType' => '' ),
'Vigencia' => array( 'totalsType' => '' ),
'Periodo' => array( 'totalsType' => '' ),
'Sector' => array( 'totalsType' => '' ),
'EntidadID' => array( 'totalsType' => '' ),
'Entidad' => array( 'totalsType' => '' ),
'codigoBPINProyecto' => array( 'totalsType' => '' ),
'Recurso' => array( 'totalsType' => '' ),
'NombreProyecto' => array( 'totalsType' => '' ),
'ObjetivoEspecificoID' => array( 'totalsType' => '' ),
'ObjetivoEspecifico' => array( 'totalsType' => '' ),
'ProductoID' => array( 'totalsType' => '' ),
'Producto' => array( 'totalsType' => '' ),
'Actividad' => array( 'totalsType' => '' ),
'Presupuesto' => array( 'totalsType' => '' ),
'DEPENDENCIA_ID' => array( 'totalsType' => '' ),
'RESPONSABLE_ID' => array( 'totalsType' => '' ),
'DEPENDENCIA_SUP_ID' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'Cod_Prod_SIIF' => array( 'totalsType' => '' ),
'Cod_Prod_SIIF_S' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Id',
'Vigencia',
'Periodo',
'Sector',
'EntidadID',
'Entidad',
'codigoBPINProyecto',
'Recurso',
'NombreProyecto',
'ObjetivoEspecificoID',
'ObjetivoEspecifico',
'ProductoID',
'Producto',
'Actividad',
'Presupuesto',
'DEPENDENCIA_ID',
'RESPONSABLE_ID',
'DEPENDENCIA_SUP_ID',
'ctrl',
'Cod_Prod_SIIF',
'Cod_Prod_SIIF_S' ),
'exportFields' => array( 'Id',
'Vigencia',
'Periodo',
'Sector',
'EntidadID',
'Entidad',
'codigoBPINProyecto',
'Recurso',
'NombreProyecto',
'ObjetivoEspecificoID',
'ObjetivoEspecifico',
'ProductoID',
'Producto',
'Actividad',
'Presupuesto',
'DEPENDENCIA_ID',
'RESPONSABLE_ID',
'DEPENDENCIA_SUP_ID',
'ctrl',
'Cod_Prod_SIIF',
'Cod_Prod_SIIF_S' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Id' => array( 'export_field' ),
'Vigencia' => array( 'export_field1' ),
'Periodo' => array( 'export_field2' ),
'Sector' => array( 'export_field3' ),
'EntidadID' => array( 'export_field4' ),
'Entidad' => array( 'export_field5' ),
'codigoBPINProyecto' => array( 'export_field6' ),
'Recurso' => array( 'export_field7' ),
'NombreProyecto' => array( 'export_field8' ),
'ObjetivoEspecificoID' => array( 'export_field9' ),
'ObjetivoEspecifico' => array( 'export_field10' ),
'ProductoID' => array( 'export_field11' ),
'Producto' => array( 'export_field12' ),
'Actividad' => array( 'export_field13' ),
'Presupuesto' => array( 'export_field14' ),
'DEPENDENCIA_ID' => array( 'export_field15' ),
'RESPONSABLE_ID' => array( 'export_field16' ),
'DEPENDENCIA_SUP_ID' => array( 'export_field17' ),
'ctrl' => array( 'export_field18' ),
'Cod_Prod_SIIF' => array( 'export_field19' ),
'Cod_Prod_SIIF_S' => array( 'export_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Vigencia',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Periodo',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Sector',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'EntidadID',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Entidad',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'codigoBPINProyecto',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Recurso',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'NombreProyecto',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'ObjetivoEspecificoID',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'ObjetivoEspecifico',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'ProductoID',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Producto',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Actividad',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Presupuesto',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'DEPENDENCIA_ID',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'RESPONSABLE_ID',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'DEPENDENCIA_SUP_ID',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'ctrl',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Cod_Prod_SIIF',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Cod_Prod_SIIF_S',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>