<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Id',
'Vigencia',
'Periodo',
'Sector',
'EntidadID',
'Entidad',
'codigoBPINProyecto',
'Recurso',
'NombreProyecto',
'ObjetivoEspecificoID',
'ObjetivoEspecifico',
'ProductoID',
'Producto',
'Actividad',
'Presupuesto',
'DEPENDENCIA_ID',
'RESPONSABLE_ID',
'DEPENDENCIA_SUP_ID',
'ctrl',
'Cod_Prod_SIIF',
'Cod_Prod_SIIF_S' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Id' => array( 'import_field' ),
'Vigencia' => array( 'import_field1' ),
'Periodo' => array( 'import_field2' ),
'Sector' => array( 'import_field3' ),
'EntidadID' => array( 'import_field4' ),
'Entidad' => array( 'import_field5' ),
'codigoBPINProyecto' => array( 'import_field6' ),
'Recurso' => array( 'import_field7' ),
'NombreProyecto' => array( 'import_field8' ),
'ObjetivoEspecificoID' => array( 'import_field9' ),
'ObjetivoEspecifico' => array( 'import_field10' ),
'ProductoID' => array( 'import_field11' ),
'Producto' => array( 'import_field12' ),
'Actividad' => array( 'import_field13' ),
'Presupuesto' => array( 'import_field14' ),
'DEPENDENCIA_ID' => array( 'import_field15' ),
'RESPONSABLE_ID' => array( 'import_field16' ),
'DEPENDENCIA_SUP_ID' => array( 'import_field17' ),
'ctrl' => array( 'import_field18' ),
'Cod_Prod_SIIF' => array( 'import_field19' ),
'Cod_Prod_SIIF_S' => array( 'import_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Vigencia',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Periodo',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Sector',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'EntidadID',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Entidad',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'codigoBPINProyecto',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Recurso',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'NombreProyecto',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'ObjetivoEspecificoID',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'ObjetivoEspecifico',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'ProductoID',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Producto',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Actividad',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Presupuesto',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'DEPENDENCIA_ID',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'RESPONSABLE_ID',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'DEPENDENCIA_SUP_ID',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'ctrl',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Cod_Prod_SIIF',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Cod_Prod_SIIF_S',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>